{
 "title": "Collabora-Online / Overview",
 "description": "This dashboard show information related to documents, processes, resource used in CO Clone",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Counters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Active View - Active  Docs",
   "type": "stat",
   "description": "Currently opened documents",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(document_active_views_active_count_total)",
     "legendFormat": "Active"
    }
   ]
  },
  {
   "title": "Total views of all docs ",
   "type": "stat",
   "description": "Total number of views (active or expired) of all documents (active and expired)",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(document_all_views_all_count_total)",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "All views",
   "type": "stat",
   "description": "Total number of views (active or expired) of all documents (active and expired).",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(document_all_views_all_count_total)",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "All Expired",
   "type": "stat",
   "description": "Total number of all views (active or expired) of expired documents",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(document_expired_views_all_count_total)",
     "legendFormat": "Expired"
    }
   ]
  },
  {
   "title": "Expired - Active",
   "type": "stat",
   "description": "Total number of expired views of all active documents",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(document_active_views_expired_count_total)",
     "legendFormat": "Expired - Active"
    }
   ]
  },
  {
   "title": "Bytes received (Since Restart)",
   "type": "stat",
   "description": "Total number of bytes received from clients by all documents (active or expired)",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(document_all_received_from_clients_total_bytes)/1048576",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes sent (Since Restart)",
   "type": "stat",
   "description": "Total number of bytes sent to clients by all documents (active or expired)",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(document_all_sent_to_clients_total_bytes)/1048576",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "coolwsd processes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(coolwsd_count)" }
   ]
  },
  {
   "title": "coolwsd threads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(coolwsd_thread_count)" }
   ]
  },
  {
   "title": "forkit processes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(forkit_count)" }
   ]
  },
  {
   "title": "forkit threads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(forkit_thread_count)" }
   ]
  },
  {
   "title": "kit processes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(kit_count)" }
   ]
  },
  {
   "title": "kit assigned",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(kit_assigned_count)" }
   ]
  },
  {
   "title": "kit unaassigned",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(kit_unassigned_count)" }
   ]
  },
  {
   "title": "kit threads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(kit_thread_count_total)" }
   ]
  },
  {
   "title": "Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Active Documents",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(document_active_views_active_count_total)",
     "legendFormat": "Active"
    }
   ]
  },
  {
   "title": "Load Duration (avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(document_all_view_load_duration_total_milliseconds[1m]))/1000",
     "legendFormat": "All"
    },
    {
     "expr": "avg(rate(document_active_view_load_duration_total_milliseconds[1m]))/1000",
     "legendFormat": "Active"
    }
   ]
  },
  {
   "title": "CPU Used",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(coolwsd_cpu_time_seconds[3m]))",
     "legendFormat": "coolwsd cpu"
    },
    {
     "expr": "sum(rate(forkit_cpu_time_seconds[3m]))",
     "legendFormat": "forkit cpu"
    },
    {
     "expr": "sum(rate(kit_cpu_time_total_seconds[3m]))",
     "legendFormat": "kit cpu"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum(coolwsd_memory_used_bytes)/1048576",
     "legendFormat": "coolwsd"
    },
    {
     "expr": "sum(forkit_memory_used_bytes)/1048576",
     "legendFormat": "forkit"
    },
    {
     "expr": "sum(kit_memory_used_total_bytes)/1048576",
     "legendFormat": "kit"
    }
   ]
  },
  {
   "title": "Byte sent to clients",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum(rate(document_all_sent_to_clients_total_bytes[1m]))/1048576",
     "legendFormat": "All"
    },
    {
     "expr": "sum(rate(document_active_sent_to_clients_total_bytes[1m]))/1048576",
     "legendFormat": "Active"
    },
    {
     "expr": "sum(rate(document_expired_sent_to_clients_total_bytes[1m]))/1048576",
     "legendFormat": "Expired"
    }
   ]
  },
  {
   "title": "Byte received from clients",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum(rate(document_all_received_from_clients_total_bytes[1m]))/1048576",
     "legendFormat": "All"
    }
   ]
  }
 ]
}